"use strict";
/**
 * Archery calculator constants.
 *
 * Compound tuning is now centered on the reverse-engineered SFAX formulas.
 * Recurve/traditional keep the previous calibrated approximation.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SFAX_REAR_MASS_REFERENCE = exports.SFAX_FLETCH_WEIGHT_REFERENCE = exports.SFAX_FRONT_MASS_REFERENCE = exports.SFAX_COMPONENT_SENSITIVITY = exports.SFAX_DYNAMIC_DEFAULT_LENGTH_FALLBACK = exports.SFAX_DYNAMIC_NON_COMPOUND_CURVE_DIVISOR = exports.SFAX_DYNAMIC_LENGTH_BASE = exports.SFAX_DYNAMIC_LENGTH_REFERENCE = exports.SFAX_DYNAMIC_LENGTH_DIVISOR = exports.SFAX_DYNAMIC_LENGTH_MULTIPLIER = exports.SFAX_DYNAMIC_FINGER_DELTA = exports.SFAX_DYNAMIC_FINGER_BASE = exports.SFAX_DYNAMIC_FINGER_END = exports.SFAX_DYNAMIC_FINGER_START = exports.SFAX_DYNAMIC_A2A_DIVISOR_NON_COMPOUND = exports.SFAX_DYNAMIC_A2A_SENSITIVITY_NON_COMPOUND = exports.SFAX_DYNAMIC_A2A_REF_NON_COMPOUND = exports.SFAX_DYNAMIC_A2A_CURVE_AMPLITUDE = exports.SFAX_DYNAMIC_A2A_CURVE_END = exports.SFAX_DYNAMIC_A2A_CURVE_START = exports.SFAX_DYNAMIC_DRAW_CURVE_AMPLITUDE_NON_COMPOUND = exports.SFAX_DYNAMIC_DRAW_CURVE_AMPLITUDE = exports.SFAX_DYNAMIC_DRAW_CURVE_END = exports.SFAX_DYNAMIC_DRAW_CURVE_START = exports.SFAX_VELOCITY_LOW_IBO_EFFICIENCY = exports.SFAX_VELOCITY_LOW_IBO_THRESHOLD = exports.SFAX_VELOCITY_DL_MICRO_FACTOR = exports.SFAX_VELOCITY_DW_MICRO_FACTOR = exports.SFAX_VELOCITY_DEFAULT_DL_FACTOR = exports.SFAX_VELOCITY_DEFAULT_DW_FACTOR = exports.SFAX_VELOCITY_DECAY_HIGH = exports.SFAX_VELOCITY_DECAY_MID = exports.SFAX_VELOCITY_WEIGHT_CLASS_START = exports.SFAX_VELOCITY_WEIGHT_CLASS_SIZE = exports.SFAX_VELOCITY_SCALING_FACTOR = exports.SFAX_VELOCITY_NON_COMPOUND_BASE_EFFICIENCY = exports.SFAX_VELOCITY_COMPOUND_BASE_EFFICIENCY = exports.SFAX_VELOCITY_NON_COMPOUND_BASE_OFFSET = exports.SFAX_VELOCITY_COMPOUND_BASE_OFFSET = exports.SFAX_VELOCITY_DIVISOR = exports.SFAX_VELOCITY_BRACE_HEIGHT_FPS = exports.SFAX_VELOCITY_DRAW_WEIGHT_FPS = exports.SFAX_SPINE_TEST_LENGTH = exports.SFAX_REFERENCE_HOLDING_PERCENT = exports.SFAX_REFERENCE_PERCENT = exports.SFAX_REFERENCE_ARROW_WEIGHT = exports.SFAX_REFERENCE_BRACE_HEIGHT = exports.SFAX_REFERENCE_DRAW_LENGTH = exports.SFAX_REFERENCE_DRAW_WEIGHT = exports.ARCHERY_TYPE = void 0;
exports.TEMP_SPINE_COEFFICIENT = exports.TEMP_REFERENCE = exports.VELOCITY_OPTIMAL_MAX = exports.VELOCITY_OPTIMAL_MIN = exports.VELOCITY_MAX_SAFE = exports.VELOCITY_MIN_TARGET = exports.FOC_OPTIMAL_HIGH = exports.FOC_OPTIMAL_LOW = exports.FOC_MAX_RECOMMENDED = exports.FOC_MIN_RECOMMENDED = exports.MASS_RATIO_MAX_RECOMMENDED = exports.MASS_RATIO_MIN_RECOMMENDED = exports.MASS_RATIO_MIN_SAFE = exports.GPP_MAX_RECOMMENDED = exports.GPP_MIN_RECOMMENDED = exports.GPP_MIN_SAFE = exports.MATCH_EXTREME_STIFF = exports.MATCH_EXTREME_WEAK = exports.MATCH_GOOD_MIN = exports.MATCH_GOOD_MAX = exports.MATCH_TOLERANCE = exports.KINETIC_ENERGY_DIVISOR = exports.K_FPS_CONVERSION = exports.K_RECURVE_CALIBRATION = exports.CAM_FDR = exports.SFAX_DEFAULT_CAM_EFFICIENCY_FACTOR = exports.SFAX_CHRONOGRAPH_MAX_RATIO = exports.SFAX_CHRONOGRAPH_MIN_RATIO = exports.SFAX_INSERT_DEPTHS = exports.SFAX_FOC_FLETCH_BASE_OFFSET = exports.SFAX_FOC_FLETCH_DIVISOR = exports.SFAX_FOC_WRAP_OFFSET = exports.SFAX_FOC_FRONT_MASS_DEPTH_MULTIPLIER = exports.SFAX_FOC_NOCK_OVERHANG = exports.SFAX_SHAFT_CATEGORY_TARGET = exports.SFAX_SHAFT_CATEGORY_HUNTING = exports.SFAX_SHAFT_CATEGORY_BASE = exports.SFAX_DACRON_CURVE_DIVISOR = exports.SFAX_DACRON_DRAW_LENGTH_CEILING = exports.SFAX_DACRON_DRAW_LENGTH_FLOOR = exports.SFAX_DACRON_MAX_ADJUSTMENT = exports.SFAX_DACRON_BASE_ADJUSTMENT = exports.SFAX_RELEASE_FACTOR_FINGER = exports.SFAX_RELEASE_FACTOR_ROPE = exports.SFAX_RELEASE_FACTOR_POST = exports.SFAX_RELEASE_FACTOR_UNKNOWN = exports.SFAX_MIN_INTERMEDIATE_SPINE = void 0;
// === ARCHERY TYPES ===
exports.ARCHERY_TYPE = {
    COMPOUND: 'compound',
    RECURVO: 'recurvo',
    TRADITIONAL: 'traditional',
};
// === SFAX COMPOUND MODEL ===
exports.SFAX_REFERENCE_DRAW_WEIGHT = 70;
exports.SFAX_REFERENCE_DRAW_LENGTH = 30;
exports.SFAX_REFERENCE_BRACE_HEIGHT = 7;
exports.SFAX_REFERENCE_ARROW_WEIGHT = 300;
exports.SFAX_REFERENCE_PERCENT = 100;
exports.SFAX_REFERENCE_HOLDING_PERCENT = 65;
exports.SFAX_SPINE_TEST_LENGTH = 28;
exports.SFAX_VELOCITY_DRAW_WEIGHT_FPS = 0.325;
exports.SFAX_VELOCITY_BRACE_HEIGHT_FPS = 10.2;
exports.SFAX_VELOCITY_DIVISOR = 5.35;
exports.SFAX_VELOCITY_COMPOUND_BASE_OFFSET = 325;
exports.SFAX_VELOCITY_NON_COMPOUND_BASE_OFFSET = 220;
exports.SFAX_VELOCITY_COMPOUND_BASE_EFFICIENCY = 82;
exports.SFAX_VELOCITY_NON_COMPOUND_BASE_EFFICIENCY = 76;
exports.SFAX_VELOCITY_SCALING_FACTOR = 1.5;
exports.SFAX_VELOCITY_WEIGHT_CLASS_SIZE = 10;
exports.SFAX_VELOCITY_WEIGHT_CLASS_START = 300;
exports.SFAX_VELOCITY_DECAY_MID = 0.55;
exports.SFAX_VELOCITY_DECAY_HIGH = 0.45;
exports.SFAX_VELOCITY_DEFAULT_DW_FACTOR = 2;
exports.SFAX_VELOCITY_DEFAULT_DL_FACTOR = 10.2;
exports.SFAX_VELOCITY_DW_MICRO_FACTOR = 0.01;
exports.SFAX_VELOCITY_DL_MICRO_FACTOR = 0.03175;
exports.SFAX_VELOCITY_LOW_IBO_THRESHOLD = 200;
exports.SFAX_VELOCITY_LOW_IBO_EFFICIENCY = 0.2;
exports.SFAX_DYNAMIC_DRAW_CURVE_START = -70;
exports.SFAX_DYNAMIC_DRAW_CURVE_END = 110;
exports.SFAX_DYNAMIC_DRAW_CURVE_AMPLITUDE = 15;
exports.SFAX_DYNAMIC_DRAW_CURVE_AMPLITUDE_NON_COMPOUND = 22;
exports.SFAX_DYNAMIC_A2A_CURVE_START = 24;
exports.SFAX_DYNAMIC_A2A_CURVE_END = 45;
exports.SFAX_DYNAMIC_A2A_CURVE_AMPLITUDE = 2;
exports.SFAX_DYNAMIC_A2A_REF_NON_COMPOUND = 60;
exports.SFAX_DYNAMIC_A2A_SENSITIVITY_NON_COMPOUND = 6.5;
exports.SFAX_DYNAMIC_A2A_DIVISOR_NON_COMPOUND = 40;
exports.SFAX_DYNAMIC_FINGER_START = 10;
exports.SFAX_DYNAMIC_FINGER_END = 60;
exports.SFAX_DYNAMIC_FINGER_BASE = 1.25;
exports.SFAX_DYNAMIC_FINGER_DELTA = 2.5;
exports.SFAX_DYNAMIC_LENGTH_MULTIPLIER = 2.75;
exports.SFAX_DYNAMIC_LENGTH_DIVISOR = 80;
exports.SFAX_DYNAMIC_LENGTH_REFERENCE = 50;
exports.SFAX_DYNAMIC_LENGTH_BASE = 20.75;
exports.SFAX_DYNAMIC_NON_COMPOUND_CURVE_DIVISOR = 40;
exports.SFAX_DYNAMIC_DEFAULT_LENGTH_FALLBACK = 20;
exports.SFAX_COMPONENT_SENSITIVITY = 0.12;
exports.SFAX_FRONT_MASS_REFERENCE = 75;
exports.SFAX_FLETCH_WEIGHT_REFERENCE = 30;
exports.SFAX_REAR_MASS_REFERENCE = 12;
exports.SFAX_MIN_INTERMEDIATE_SPINE = 15;
exports.SFAX_RELEASE_FACTOR_UNKNOWN = 0.25;
exports.SFAX_RELEASE_FACTOR_POST = 1.0;
exports.SFAX_RELEASE_FACTOR_ROPE = 1.75;
exports.SFAX_RELEASE_FACTOR_FINGER = 5.0;
exports.SFAX_DACRON_BASE_ADJUSTMENT = 3;
exports.SFAX_DACRON_MAX_ADJUSTMENT = 5;
exports.SFAX_DACRON_DRAW_LENGTH_FLOOR = 14;
exports.SFAX_DACRON_DRAW_LENGTH_CEILING = 35;
exports.SFAX_DACRON_CURVE_DIVISOR = 21;
exports.SFAX_SHAFT_CATEGORY_BASE = 0.00421875;
exports.SFAX_SHAFT_CATEGORY_HUNTING = 0.01265625;
exports.SFAX_SHAFT_CATEGORY_TARGET = 0.02109375;
exports.SFAX_FOC_NOCK_OVERHANG = 0.5;
exports.SFAX_FOC_FRONT_MASS_DEPTH_MULTIPLIER = 0.75;
exports.SFAX_FOC_WRAP_OFFSET = 3;
exports.SFAX_FOC_FLETCH_DIVISOR = 3;
exports.SFAX_FOC_FLETCH_BASE_OFFSET = 1;
exports.SFAX_INSERT_DEPTHS = {
    default: 0.65,
    shallow: 0.75,
    halfOutsert: 1.25,
    fullOutsert: 1.5,
    extendedOutsert: 1.75,
};
// Chronograph should refine the SFAX target, not replace the model wholesale.
exports.SFAX_CHRONOGRAPH_MIN_RATIO = 0.85;
exports.SFAX_CHRONOGRAPH_MAX_RATIO = 1.15;
exports.SFAX_DEFAULT_CAM_EFFICIENCY_FACTOR = 0.00000104;
// === CAM FDR (Force-Draw Ratio) ===
exports.CAM_FDR = {
    round: 0.35,
    medium: 0.45,
    aggressive: 0.55,
    speed: 0.65,
    max: 0.75,
};
// === RECURVE / TRADITIONAL CALIBRATION ===
exports.K_RECURVE_CALIBRATION = 0.50;
// === VELOCITY / ENERGY CONVERSION ===
exports.K_FPS_CONVERSION = 546000;
exports.KINETIC_ENERGY_DIVISOR = 450240;
// === MATCH TOLERANCE ===
exports.MATCH_TOLERANCE = 0.10;
exports.MATCH_GOOD_MAX = 1 + exports.MATCH_TOLERANCE;
exports.MATCH_GOOD_MIN = 1 - exports.MATCH_TOLERANCE;
exports.MATCH_EXTREME_WEAK = 1.25;
exports.MATCH_EXTREME_STIFF = 0.75;
// === MASS RATIO THRESHOLDS ===
exports.GPP_MIN_SAFE = 4;
exports.GPP_MIN_RECOMMENDED = 5;
exports.GPP_MAX_RECOMMENDED = 8;
exports.MASS_RATIO_MIN_SAFE = 4;
exports.MASS_RATIO_MIN_RECOMMENDED = 5;
exports.MASS_RATIO_MAX_RECOMMENDED = 8;
// === FOC / SPEED RECOMMENDATION THRESHOLDS ===
exports.FOC_MIN_RECOMMENDED = 7;
exports.FOC_MAX_RECOMMENDED = 16;
exports.FOC_OPTIMAL_LOW = 13;
exports.FOC_OPTIMAL_HIGH = 15;
exports.VELOCITY_MIN_TARGET = 260;
exports.VELOCITY_MAX_SAFE = 340;
exports.VELOCITY_OPTIMAL_MIN = 280;
exports.VELOCITY_OPTIMAL_MAX = 320;
// === TEMPERATURE CALIBRATION ===
exports.TEMP_REFERENCE = 70;
exports.TEMP_SPINE_COEFFICIENT = 0.001;
